variables:
  IMAGE: node:10-alpine

stages:
  - test

before_script:
  - npm install

unit tests:
  stage: test
  image: $IMAGE
  script:
    - npm run test:unit

lint:
  stage: test
  image: $IMAGE
  script:
    - npm run test:lint

ts:
  stage: test
  image: $IMAGE
  script:
    - npm run test:ts
